print("Hello")
print()
print("Welcome", end=" ")
print("to gfg")
print("10", "2", "23", sep="-")
number = input("Enter roll number ")
name = input("Enter age ")

print("\n")
print('Roll number:', number, 'Name:', name)
print("Printing type of a input values")
print("type of number", type(number))
print("type of name", type(name))